//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarduckCRM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BarduckCRMEntities : DbContext
    {
        public BarduckCRMEntities()
            : base("name=BarduckCRMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<S_Baglanti_Result> S_Baglanti(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_Baglanti_Result>("S_Baglanti", iDParameter);
        }
    
        public virtual ObjectResult<S_Tip_Result> S_Tip(Nullable<int> tipUstID)
        {
            var tipUstIDParameter = tipUstID.HasValue ?
                new ObjectParameter("TipUstID", tipUstID) :
                new ObjectParameter("TipUstID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_Tip_Result>("S_Tip", tipUstIDParameter);
        }
    
        public virtual ObjectResult<S_KullaniciAyarlari_Result> S_KullaniciAyarlari(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_KullaniciAyarlari_Result>("S_KullaniciAyarlari", iDParameter);
        }
    
        public virtual ObjectResult<S_Form_Result> S_Form(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_Form_Result>("S_Form", iDParameter);
        }
    
        public virtual ObjectResult<IUD_Baglanti_Result> IUD_Baglanti(Nullable<bool> sil, Nullable<int> iD, string adi, string adiSoyadi, string adres, Nullable<bool> aktif, Nullable<bool> bireysel, string cepTel, Nullable<int> cinsiyet, string dahili, Nullable<System.DateTime> dogumTarihi, string email, string evTel, Nullable<int> firmaID, string isTel, Nullable<int> kullaniciID, Nullable<bool> kurumsal, Nullable<int> medeniHali_TipID44, Nullable<int> meslek_TipID2, string notlar, Nullable<int> onekID, string postaKodu, Nullable<int> puan, Nullable<int> reyting, string sehir, string semt, string soyadi, Nullable<bool> tanitimCepTel, Nullable<bool> tanitimEPosta, Nullable<bool> tanitimEvTel, Nullable<bool> tanitimIsTel, Nullable<System.DateTime> tarih, string ulke, Nullable<int> ulkeID, string unvan, Nullable<int> uyruguID)
        {
            var silParameter = sil.HasValue ?
                new ObjectParameter("Sil", sil) :
                new ObjectParameter("Sil", typeof(bool));
    
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var adiParameter = adi != null ?
                new ObjectParameter("Adi", adi) :
                new ObjectParameter("Adi", typeof(string));
    
            var adiSoyadiParameter = adiSoyadi != null ?
                new ObjectParameter("AdiSoyadi", adiSoyadi) :
                new ObjectParameter("AdiSoyadi", typeof(string));
    
            var adresParameter = adres != null ?
                new ObjectParameter("Adres", adres) :
                new ObjectParameter("Adres", typeof(string));
    
            var aktifParameter = aktif.HasValue ?
                new ObjectParameter("Aktif", aktif) :
                new ObjectParameter("Aktif", typeof(bool));
    
            var bireyselParameter = bireysel.HasValue ?
                new ObjectParameter("Bireysel", bireysel) :
                new ObjectParameter("Bireysel", typeof(bool));
    
            var cepTelParameter = cepTel != null ?
                new ObjectParameter("CepTel", cepTel) :
                new ObjectParameter("CepTel", typeof(string));
    
            var cinsiyetParameter = cinsiyet.HasValue ?
                new ObjectParameter("Cinsiyet", cinsiyet) :
                new ObjectParameter("Cinsiyet", typeof(int));
    
            var dahiliParameter = dahili != null ?
                new ObjectParameter("Dahili", dahili) :
                new ObjectParameter("Dahili", typeof(string));
    
            var dogumTarihiParameter = dogumTarihi.HasValue ?
                new ObjectParameter("DogumTarihi", dogumTarihi) :
                new ObjectParameter("DogumTarihi", typeof(System.DateTime));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var evTelParameter = evTel != null ?
                new ObjectParameter("EvTel", evTel) :
                new ObjectParameter("EvTel", typeof(string));
    
            var firmaIDParameter = firmaID.HasValue ?
                new ObjectParameter("FirmaID", firmaID) :
                new ObjectParameter("FirmaID", typeof(int));
    
            var isTelParameter = isTel != null ?
                new ObjectParameter("IsTel", isTel) :
                new ObjectParameter("IsTel", typeof(string));
    
            var kullaniciIDParameter = kullaniciID.HasValue ?
                new ObjectParameter("KullaniciID", kullaniciID) :
                new ObjectParameter("KullaniciID", typeof(int));
    
            var kurumsalParameter = kurumsal.HasValue ?
                new ObjectParameter("Kurumsal", kurumsal) :
                new ObjectParameter("Kurumsal", typeof(bool));
    
            var medeniHali_TipID44Parameter = medeniHali_TipID44.HasValue ?
                new ObjectParameter("MedeniHali_TipID44", medeniHali_TipID44) :
                new ObjectParameter("MedeniHali_TipID44", typeof(int));
    
            var meslek_TipID2Parameter = meslek_TipID2.HasValue ?
                new ObjectParameter("Meslek_TipID2", meslek_TipID2) :
                new ObjectParameter("Meslek_TipID2", typeof(int));
    
            var notlarParameter = notlar != null ?
                new ObjectParameter("Notlar", notlar) :
                new ObjectParameter("Notlar", typeof(string));
    
            var onekIDParameter = onekID.HasValue ?
                new ObjectParameter("OnekID", onekID) :
                new ObjectParameter("OnekID", typeof(int));
    
            var postaKoduParameter = postaKodu != null ?
                new ObjectParameter("PostaKodu", postaKodu) :
                new ObjectParameter("PostaKodu", typeof(string));
    
            var puanParameter = puan.HasValue ?
                new ObjectParameter("Puan", puan) :
                new ObjectParameter("Puan", typeof(int));
    
            var reytingParameter = reyting.HasValue ?
                new ObjectParameter("Reyting", reyting) :
                new ObjectParameter("Reyting", typeof(int));
    
            var sehirParameter = sehir != null ?
                new ObjectParameter("Sehir", sehir) :
                new ObjectParameter("Sehir", typeof(string));
    
            var semtParameter = semt != null ?
                new ObjectParameter("Semt", semt) :
                new ObjectParameter("Semt", typeof(string));
    
            var soyadiParameter = soyadi != null ?
                new ObjectParameter("Soyadi", soyadi) :
                new ObjectParameter("Soyadi", typeof(string));
    
            var tanitimCepTelParameter = tanitimCepTel.HasValue ?
                new ObjectParameter("TanitimCepTel", tanitimCepTel) :
                new ObjectParameter("TanitimCepTel", typeof(bool));
    
            var tanitimEPostaParameter = tanitimEPosta.HasValue ?
                new ObjectParameter("TanitimEPosta", tanitimEPosta) :
                new ObjectParameter("TanitimEPosta", typeof(bool));
    
            var tanitimEvTelParameter = tanitimEvTel.HasValue ?
                new ObjectParameter("TanitimEvTel", tanitimEvTel) :
                new ObjectParameter("TanitimEvTel", typeof(bool));
    
            var tanitimIsTelParameter = tanitimIsTel.HasValue ?
                new ObjectParameter("TanitimIsTel", tanitimIsTel) :
                new ObjectParameter("TanitimIsTel", typeof(bool));
    
            var tarihParameter = tarih.HasValue ?
                new ObjectParameter("Tarih", tarih) :
                new ObjectParameter("Tarih", typeof(System.DateTime));
    
            var ulkeParameter = ulke != null ?
                new ObjectParameter("Ulke", ulke) :
                new ObjectParameter("Ulke", typeof(string));
    
            var ulkeIDParameter = ulkeID.HasValue ?
                new ObjectParameter("UlkeID", ulkeID) :
                new ObjectParameter("UlkeID", typeof(int));
    
            var unvanParameter = unvan != null ?
                new ObjectParameter("Unvan", unvan) :
                new ObjectParameter("Unvan", typeof(string));
    
            var uyruguIDParameter = uyruguID.HasValue ?
                new ObjectParameter("UyruguID", uyruguID) :
                new ObjectParameter("UyruguID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IUD_Baglanti_Result>("IUD_Baglanti", silParameter, iDParameter, adiParameter, adiSoyadiParameter, adresParameter, aktifParameter, bireyselParameter, cepTelParameter, cinsiyetParameter, dahiliParameter, dogumTarihiParameter, emailParameter, evTelParameter, firmaIDParameter, isTelParameter, kullaniciIDParameter, kurumsalParameter, medeniHali_TipID44Parameter, meslek_TipID2Parameter, notlarParameter, onekIDParameter, postaKoduParameter, puanParameter, reytingParameter, sehirParameter, semtParameter, soyadiParameter, tanitimCepTelParameter, tanitimEPostaParameter, tanitimEvTelParameter, tanitimIsTelParameter, tarihParameter, ulkeParameter, ulkeIDParameter, unvanParameter, uyruguIDParameter);
        }
    
        public virtual ObjectResult<S_Ulke_Result> S_Ulke(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_Ulke_Result>("S_Ulke", iDParameter);
        }
    
        public virtual ObjectResult<S_Firma_Result> S_Firma(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_Firma_Result>("S_Firma", iDParameter);
        }
    
        public virtual ObjectResult<S_TipResimli_Result> S_TipResimli(Nullable<int> tipUstID)
        {
            var tipUstIDParameter = tipUstID.HasValue ?
                new ObjectParameter("TipUstID", tipUstID) :
                new ObjectParameter("TipUstID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_TipResimli_Result>("S_TipResimli", tipUstIDParameter);
        }
    
        public virtual ObjectResult<S_Proje_Result> S_Proje(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_Proje_Result>("S_Proje", iDParameter);
        }
    
        public virtual ObjectResult<IUD_Proje_Result> IUD_Proje(Nullable<bool> sil, Nullable<int> iD, string projeKodu, string projeAdi, Nullable<System.DateTime> imalatBaslangic, Nullable<System.DateTime> imalatBitis, Nullable<System.DateTime> satisBaslangic, Nullable<System.DateTime> satisBitis, Nullable<System.DateTime> tarih, Nullable<bool> aktif, Nullable<bool> satisaUygun, Nullable<bool> teslimeUygun, Nullable<int> firmaID, Nullable<int> kullaniciID)
        {
            var silParameter = sil.HasValue ?
                new ObjectParameter("Sil", sil) :
                new ObjectParameter("Sil", typeof(bool));
    
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var projeKoduParameter = projeKodu != null ?
                new ObjectParameter("ProjeKodu", projeKodu) :
                new ObjectParameter("ProjeKodu", typeof(string));
    
            var projeAdiParameter = projeAdi != null ?
                new ObjectParameter("ProjeAdi", projeAdi) :
                new ObjectParameter("ProjeAdi", typeof(string));
    
            var imalatBaslangicParameter = imalatBaslangic.HasValue ?
                new ObjectParameter("ImalatBaslangic", imalatBaslangic) :
                new ObjectParameter("ImalatBaslangic", typeof(System.DateTime));
    
            var imalatBitisParameter = imalatBitis.HasValue ?
                new ObjectParameter("ImalatBitis", imalatBitis) :
                new ObjectParameter("ImalatBitis", typeof(System.DateTime));
    
            var satisBaslangicParameter = satisBaslangic.HasValue ?
                new ObjectParameter("SatisBaslangic", satisBaslangic) :
                new ObjectParameter("SatisBaslangic", typeof(System.DateTime));
    
            var satisBitisParameter = satisBitis.HasValue ?
                new ObjectParameter("SatisBitis", satisBitis) :
                new ObjectParameter("SatisBitis", typeof(System.DateTime));
    
            var tarihParameter = tarih.HasValue ?
                new ObjectParameter("Tarih", tarih) :
                new ObjectParameter("Tarih", typeof(System.DateTime));
    
            var aktifParameter = aktif.HasValue ?
                new ObjectParameter("Aktif", aktif) :
                new ObjectParameter("Aktif", typeof(bool));
    
            var satisaUygunParameter = satisaUygun.HasValue ?
                new ObjectParameter("SatisaUygun", satisaUygun) :
                new ObjectParameter("SatisaUygun", typeof(bool));
    
            var teslimeUygunParameter = teslimeUygun.HasValue ?
                new ObjectParameter("TeslimeUygun", teslimeUygun) :
                new ObjectParameter("TeslimeUygun", typeof(bool));
    
            var firmaIDParameter = firmaID.HasValue ?
                new ObjectParameter("FirmaID", firmaID) :
                new ObjectParameter("FirmaID", typeof(int));
    
            var kullaniciIDParameter = kullaniciID.HasValue ?
                new ObjectParameter("KullaniciID", kullaniciID) :
                new ObjectParameter("KullaniciID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IUD_Proje_Result>("IUD_Proje", silParameter, iDParameter, projeKoduParameter, projeAdiParameter, imalatBaslangicParameter, imalatBitisParameter, satisBaslangicParameter, satisBitisParameter, tarihParameter, aktifParameter, satisaUygunParameter, teslimeUygunParameter, firmaIDParameter, kullaniciIDParameter);
        }
    
        public virtual ObjectResult<IUD_Firma_Result> IUD_Firma(Nullable<bool> sil, Nullable<int> iD, string firmaAdi, string firmaKodu, Nullable<bool> aktif, Nullable<int> aktifKullaniciID)
        {
            var silParameter = sil.HasValue ?
                new ObjectParameter("Sil", sil) :
                new ObjectParameter("Sil", typeof(bool));
    
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var firmaAdiParameter = firmaAdi != null ?
                new ObjectParameter("FirmaAdi", firmaAdi) :
                new ObjectParameter("FirmaAdi", typeof(string));
    
            var firmaKoduParameter = firmaKodu != null ?
                new ObjectParameter("FirmaKodu", firmaKodu) :
                new ObjectParameter("FirmaKodu", typeof(string));
    
            var aktifParameter = aktif.HasValue ?
                new ObjectParameter("Aktif", aktif) :
                new ObjectParameter("Aktif", typeof(bool));
    
            var aktifKullaniciIDParameter = aktifKullaniciID.HasValue ?
                new ObjectParameter("AktifKullaniciID", aktifKullaniciID) :
                new ObjectParameter("AktifKullaniciID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IUD_Firma_Result>("IUD_Firma", silParameter, iDParameter, firmaAdiParameter, firmaKoduParameter, aktifParameter, aktifKullaniciIDParameter);
        }
    
        public virtual ObjectResult<IUD_Ofis_Result> IUD_Ofis(Nullable<bool> sil, Nullable<int> kullaniciID, Nullable<int> iD, Nullable<int> firmaID, string ofisKodu, string ofisAdi, Nullable<int> ulkeID, string sehir, string semt, string adres, Nullable<int> yetkiliPersonelID, Nullable<int> karsilamaPersoneliID, Nullable<bool> aktif, Nullable<System.DateTime> tarih, Nullable<int> olusturanKullaniciID, Nullable<System.DateTime> olusturanTarih, Nullable<int> degistirenKullaniciID, Nullable<System.DateTime> degistirenTarih)
        {
            var silParameter = sil.HasValue ?
                new ObjectParameter("Sil", sil) :
                new ObjectParameter("Sil", typeof(bool));
    
            var kullaniciIDParameter = kullaniciID.HasValue ?
                new ObjectParameter("KullaniciID", kullaniciID) :
                new ObjectParameter("KullaniciID", typeof(int));
    
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var firmaIDParameter = firmaID.HasValue ?
                new ObjectParameter("FirmaID", firmaID) :
                new ObjectParameter("FirmaID", typeof(int));
    
            var ofisKoduParameter = ofisKodu != null ?
                new ObjectParameter("OfisKodu", ofisKodu) :
                new ObjectParameter("OfisKodu", typeof(string));
    
            var ofisAdiParameter = ofisAdi != null ?
                new ObjectParameter("OfisAdi", ofisAdi) :
                new ObjectParameter("OfisAdi", typeof(string));
    
            var ulkeIDParameter = ulkeID.HasValue ?
                new ObjectParameter("UlkeID", ulkeID) :
                new ObjectParameter("UlkeID", typeof(int));
    
            var sehirParameter = sehir != null ?
                new ObjectParameter("Sehir", sehir) :
                new ObjectParameter("Sehir", typeof(string));
    
            var semtParameter = semt != null ?
                new ObjectParameter("Semt", semt) :
                new ObjectParameter("Semt", typeof(string));
    
            var adresParameter = adres != null ?
                new ObjectParameter("Adres", adres) :
                new ObjectParameter("Adres", typeof(string));
    
            var yetkiliPersonelIDParameter = yetkiliPersonelID.HasValue ?
                new ObjectParameter("YetkiliPersonelID", yetkiliPersonelID) :
                new ObjectParameter("YetkiliPersonelID", typeof(int));
    
            var karsilamaPersoneliIDParameter = karsilamaPersoneliID.HasValue ?
                new ObjectParameter("KarsilamaPersoneliID", karsilamaPersoneliID) :
                new ObjectParameter("KarsilamaPersoneliID", typeof(int));
    
            var aktifParameter = aktif.HasValue ?
                new ObjectParameter("Aktif", aktif) :
                new ObjectParameter("Aktif", typeof(bool));
    
            var tarihParameter = tarih.HasValue ?
                new ObjectParameter("Tarih", tarih) :
                new ObjectParameter("Tarih", typeof(System.DateTime));
    
            var olusturanKullaniciIDParameter = olusturanKullaniciID.HasValue ?
                new ObjectParameter("OlusturanKullaniciID", olusturanKullaniciID) :
                new ObjectParameter("OlusturanKullaniciID", typeof(int));
    
            var olusturanTarihParameter = olusturanTarih.HasValue ?
                new ObjectParameter("OlusturanTarih", olusturanTarih) :
                new ObjectParameter("OlusturanTarih", typeof(System.DateTime));
    
            var degistirenKullaniciIDParameter = degistirenKullaniciID.HasValue ?
                new ObjectParameter("DegistirenKullaniciID", degistirenKullaniciID) :
                new ObjectParameter("DegistirenKullaniciID", typeof(int));
    
            var degistirenTarihParameter = degistirenTarih.HasValue ?
                new ObjectParameter("DegistirenTarih", degistirenTarih) :
                new ObjectParameter("DegistirenTarih", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IUD_Ofis_Result>("IUD_Ofis", silParameter, kullaniciIDParameter, iDParameter, firmaIDParameter, ofisKoduParameter, ofisAdiParameter, ulkeIDParameter, sehirParameter, semtParameter, adresParameter, yetkiliPersonelIDParameter, karsilamaPersoneliIDParameter, aktifParameter, tarihParameter, olusturanKullaniciIDParameter, olusturanTarihParameter, degistirenKullaniciIDParameter, degistirenTarihParameter);
        }
    
        public virtual ObjectResult<IUD_Personel_Result> IUD_Personel(Nullable<bool> sil, Nullable<int> iD, string adi, Nullable<int> departman_TipID1, string adres, string sehir, Nullable<int> ulkeID, string cepTel, string evTel, Nullable<System.DateTime> tarih, string email, Nullable<bool> aktif, string skype, string soyadi, Nullable<int> cinsiyeti_TipID72, Nullable<System.DateTime> dogumTarihi, Nullable<int> olusturanKullaniciID, Nullable<System.DateTime> olusturanTarih, Nullable<int> degistirenKullaniciID, Nullable<System.DateTime> degistirenTarih, string unvan, Nullable<int> onekID, string semt, string postaKodu, Nullable<int> ofisID, Nullable<int> personelTakimID, Nullable<System.DateTime> iseBanlangicTarihi, Nullable<System.DateTime> istenAyrilisTarihi)
        {
            var silParameter = sil.HasValue ?
                new ObjectParameter("Sil", sil) :
                new ObjectParameter("Sil", typeof(bool));
    
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var adiParameter = adi != null ?
                new ObjectParameter("Adi", adi) :
                new ObjectParameter("Adi", typeof(string));
    
            var departman_TipID1Parameter = departman_TipID1.HasValue ?
                new ObjectParameter("Departman_TipID1", departman_TipID1) :
                new ObjectParameter("Departman_TipID1", typeof(int));
    
            var adresParameter = adres != null ?
                new ObjectParameter("Adres", adres) :
                new ObjectParameter("Adres", typeof(string));
    
            var sehirParameter = sehir != null ?
                new ObjectParameter("Sehir", sehir) :
                new ObjectParameter("Sehir", typeof(string));
    
            var ulkeIDParameter = ulkeID.HasValue ?
                new ObjectParameter("UlkeID", ulkeID) :
                new ObjectParameter("UlkeID", typeof(int));
    
            var cepTelParameter = cepTel != null ?
                new ObjectParameter("CepTel", cepTel) :
                new ObjectParameter("CepTel", typeof(string));
    
            var evTelParameter = evTel != null ?
                new ObjectParameter("EvTel", evTel) :
                new ObjectParameter("EvTel", typeof(string));
    
            var tarihParameter = tarih.HasValue ?
                new ObjectParameter("Tarih", tarih) :
                new ObjectParameter("Tarih", typeof(System.DateTime));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var aktifParameter = aktif.HasValue ?
                new ObjectParameter("Aktif", aktif) :
                new ObjectParameter("Aktif", typeof(bool));
    
            var skypeParameter = skype != null ?
                new ObjectParameter("Skype", skype) :
                new ObjectParameter("Skype", typeof(string));
    
            var soyadiParameter = soyadi != null ?
                new ObjectParameter("Soyadi", soyadi) :
                new ObjectParameter("Soyadi", typeof(string));
    
            var cinsiyeti_TipID72Parameter = cinsiyeti_TipID72.HasValue ?
                new ObjectParameter("Cinsiyeti_TipID72", cinsiyeti_TipID72) :
                new ObjectParameter("Cinsiyeti_TipID72", typeof(int));
    
            var dogumTarihiParameter = dogumTarihi.HasValue ?
                new ObjectParameter("DogumTarihi", dogumTarihi) :
                new ObjectParameter("DogumTarihi", typeof(System.DateTime));
    
            var olusturanKullaniciIDParameter = olusturanKullaniciID.HasValue ?
                new ObjectParameter("OlusturanKullaniciID", olusturanKullaniciID) :
                new ObjectParameter("OlusturanKullaniciID", typeof(int));
    
            var olusturanTarihParameter = olusturanTarih.HasValue ?
                new ObjectParameter("OlusturanTarih", olusturanTarih) :
                new ObjectParameter("OlusturanTarih", typeof(System.DateTime));
    
            var degistirenKullaniciIDParameter = degistirenKullaniciID.HasValue ?
                new ObjectParameter("DegistirenKullaniciID", degistirenKullaniciID) :
                new ObjectParameter("DegistirenKullaniciID", typeof(int));
    
            var degistirenTarihParameter = degistirenTarih.HasValue ?
                new ObjectParameter("DegistirenTarih", degistirenTarih) :
                new ObjectParameter("DegistirenTarih", typeof(System.DateTime));
    
            var unvanParameter = unvan != null ?
                new ObjectParameter("Unvan", unvan) :
                new ObjectParameter("Unvan", typeof(string));
    
            var onekIDParameter = onekID.HasValue ?
                new ObjectParameter("OnekID", onekID) :
                new ObjectParameter("OnekID", typeof(int));
    
            var semtParameter = semt != null ?
                new ObjectParameter("Semt", semt) :
                new ObjectParameter("Semt", typeof(string));
    
            var postaKoduParameter = postaKodu != null ?
                new ObjectParameter("PostaKodu", postaKodu) :
                new ObjectParameter("PostaKodu", typeof(string));
    
            var ofisIDParameter = ofisID.HasValue ?
                new ObjectParameter("OfisID", ofisID) :
                new ObjectParameter("OfisID", typeof(int));
    
            var personelTakimIDParameter = personelTakimID.HasValue ?
                new ObjectParameter("PersonelTakimID", personelTakimID) :
                new ObjectParameter("PersonelTakimID", typeof(int));
    
            var iseBanlangicTarihiParameter = iseBanlangicTarihi.HasValue ?
                new ObjectParameter("IseBanlangicTarihi", iseBanlangicTarihi) :
                new ObjectParameter("IseBanlangicTarihi", typeof(System.DateTime));
    
            var istenAyrilisTarihiParameter = istenAyrilisTarihi.HasValue ?
                new ObjectParameter("IstenAyrilisTarihi", istenAyrilisTarihi) :
                new ObjectParameter("IstenAyrilisTarihi", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IUD_Personel_Result>("IUD_Personel", silParameter, iDParameter, adiParameter, departman_TipID1Parameter, adresParameter, sehirParameter, ulkeIDParameter, cepTelParameter, evTelParameter, tarihParameter, emailParameter, aktifParameter, skypeParameter, soyadiParameter, cinsiyeti_TipID72Parameter, dogumTarihiParameter, olusturanKullaniciIDParameter, olusturanTarihParameter, degistirenKullaniciIDParameter, degistirenTarihParameter, unvanParameter, onekIDParameter, semtParameter, postaKoduParameter, ofisIDParameter, personelTakimIDParameter, iseBanlangicTarihiParameter, istenAyrilisTarihiParameter);
        }
    
        public virtual ObjectResult<IUD_Vaziyet_Result> IUD_Vaziyet(Nullable<bool> sil, Nullable<int> iD, Nullable<int> projeID, string adres, Nullable<decimal> metrekare, string paftaNo, string ciltNo, string sehir, string ilce, string mahalle, string koy, string bucak, string sokak, string adaNo, string yevmiyeNo, string sahifeNo, string siraNo, string haritaEnlem, string haritaBoylam, string vaziyetAdi, string vaziyetKodu, string yapiAdedi, string kapiAdedi, Nullable<decimal> yesilAlan, Nullable<int> vaziyetResimID, Nullable<System.DateTime> tarih, Nullable<bool> aktif, Nullable<System.DateTime> olusturanTarih, Nullable<int> olusturanKullaniciID, Nullable<System.DateTime> degistirenTarih, Nullable<int> degistirenKullaniciID)
        {
            var silParameter = sil.HasValue ?
                new ObjectParameter("Sil", sil) :
                new ObjectParameter("Sil", typeof(bool));
    
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var projeIDParameter = projeID.HasValue ?
                new ObjectParameter("ProjeID", projeID) :
                new ObjectParameter("ProjeID", typeof(int));
    
            var adresParameter = adres != null ?
                new ObjectParameter("Adres", adres) :
                new ObjectParameter("Adres", typeof(string));
    
            var metrekareParameter = metrekare.HasValue ?
                new ObjectParameter("Metrekare", metrekare) :
                new ObjectParameter("Metrekare", typeof(decimal));
    
            var paftaNoParameter = paftaNo != null ?
                new ObjectParameter("PaftaNo", paftaNo) :
                new ObjectParameter("PaftaNo", typeof(string));
    
            var ciltNoParameter = ciltNo != null ?
                new ObjectParameter("CiltNo", ciltNo) :
                new ObjectParameter("CiltNo", typeof(string));
    
            var sehirParameter = sehir != null ?
                new ObjectParameter("Sehir", sehir) :
                new ObjectParameter("Sehir", typeof(string));
    
            var ilceParameter = ilce != null ?
                new ObjectParameter("Ilce", ilce) :
                new ObjectParameter("Ilce", typeof(string));
    
            var mahalleParameter = mahalle != null ?
                new ObjectParameter("Mahalle", mahalle) :
                new ObjectParameter("Mahalle", typeof(string));
    
            var koyParameter = koy != null ?
                new ObjectParameter("Koy", koy) :
                new ObjectParameter("Koy", typeof(string));
    
            var bucakParameter = bucak != null ?
                new ObjectParameter("Bucak", bucak) :
                new ObjectParameter("Bucak", typeof(string));
    
            var sokakParameter = sokak != null ?
                new ObjectParameter("Sokak", sokak) :
                new ObjectParameter("Sokak", typeof(string));
    
            var adaNoParameter = adaNo != null ?
                new ObjectParameter("AdaNo", adaNo) :
                new ObjectParameter("AdaNo", typeof(string));
    
            var yevmiyeNoParameter = yevmiyeNo != null ?
                new ObjectParameter("YevmiyeNo", yevmiyeNo) :
                new ObjectParameter("YevmiyeNo", typeof(string));
    
            var sahifeNoParameter = sahifeNo != null ?
                new ObjectParameter("SahifeNo", sahifeNo) :
                new ObjectParameter("SahifeNo", typeof(string));
    
            var siraNoParameter = siraNo != null ?
                new ObjectParameter("SiraNo", siraNo) :
                new ObjectParameter("SiraNo", typeof(string));
    
            var haritaEnlemParameter = haritaEnlem != null ?
                new ObjectParameter("HaritaEnlem", haritaEnlem) :
                new ObjectParameter("HaritaEnlem", typeof(string));
    
            var haritaBoylamParameter = haritaBoylam != null ?
                new ObjectParameter("HaritaBoylam", haritaBoylam) :
                new ObjectParameter("HaritaBoylam", typeof(string));
    
            var vaziyetAdiParameter = vaziyetAdi != null ?
                new ObjectParameter("VaziyetAdi", vaziyetAdi) :
                new ObjectParameter("VaziyetAdi", typeof(string));
    
            var vaziyetKoduParameter = vaziyetKodu != null ?
                new ObjectParameter("VaziyetKodu", vaziyetKodu) :
                new ObjectParameter("VaziyetKodu", typeof(string));
    
            var yapiAdediParameter = yapiAdedi != null ?
                new ObjectParameter("YapiAdedi", yapiAdedi) :
                new ObjectParameter("YapiAdedi", typeof(string));
    
            var kapiAdediParameter = kapiAdedi != null ?
                new ObjectParameter("KapiAdedi", kapiAdedi) :
                new ObjectParameter("KapiAdedi", typeof(string));
    
            var yesilAlanParameter = yesilAlan.HasValue ?
                new ObjectParameter("YesilAlan", yesilAlan) :
                new ObjectParameter("YesilAlan", typeof(decimal));
    
            var vaziyetResimIDParameter = vaziyetResimID.HasValue ?
                new ObjectParameter("VaziyetResimID", vaziyetResimID) :
                new ObjectParameter("VaziyetResimID", typeof(int));
    
            var tarihParameter = tarih.HasValue ?
                new ObjectParameter("Tarih", tarih) :
                new ObjectParameter("Tarih", typeof(System.DateTime));
    
            var aktifParameter = aktif.HasValue ?
                new ObjectParameter("Aktif", aktif) :
                new ObjectParameter("Aktif", typeof(bool));
    
            var olusturanTarihParameter = olusturanTarih.HasValue ?
                new ObjectParameter("OlusturanTarih", olusturanTarih) :
                new ObjectParameter("OlusturanTarih", typeof(System.DateTime));
    
            var olusturanKullaniciIDParameter = olusturanKullaniciID.HasValue ?
                new ObjectParameter("OlusturanKullaniciID", olusturanKullaniciID) :
                new ObjectParameter("OlusturanKullaniciID", typeof(int));
    
            var degistirenTarihParameter = degistirenTarih.HasValue ?
                new ObjectParameter("DegistirenTarih", degistirenTarih) :
                new ObjectParameter("DegistirenTarih", typeof(System.DateTime));
    
            var degistirenKullaniciIDParameter = degistirenKullaniciID.HasValue ?
                new ObjectParameter("DegistirenKullaniciID", degistirenKullaniciID) :
                new ObjectParameter("DegistirenKullaniciID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IUD_Vaziyet_Result>("IUD_Vaziyet", silParameter, iDParameter, projeIDParameter, adresParameter, metrekareParameter, paftaNoParameter, ciltNoParameter, sehirParameter, ilceParameter, mahalleParameter, koyParameter, bucakParameter, sokakParameter, adaNoParameter, yevmiyeNoParameter, sahifeNoParameter, siraNoParameter, haritaEnlemParameter, haritaBoylamParameter, vaziyetAdiParameter, vaziyetKoduParameter, yapiAdediParameter, kapiAdediParameter, yesilAlanParameter, vaziyetResimIDParameter, tarihParameter, aktifParameter, olusturanTarihParameter, olusturanKullaniciIDParameter, degistirenTarihParameter, degistirenKullaniciIDParameter);
        }
    
        public virtual ObjectResult<S_Vaziyet_Result> S_Vaziyet(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_Vaziyet_Result>("S_Vaziyet", iDParameter);
        }
    
        public virtual ObjectResult<S_SadakatPuaniHesapla_Result> S_SadakatPuaniHesapla(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_SadakatPuaniHesapla_Result>("S_SadakatPuaniHesapla", iDParameter);
        }
    
        public virtual int IUD_SadakatPuaniHesapla(Nullable<int> baglantiID, Nullable<decimal> puan, string aciklama, Nullable<System.DateTime> tarih, Nullable<int> puanKategorisi)
        {
            var baglantiIDParameter = baglantiID.HasValue ?
                new ObjectParameter("BaglantiID", baglantiID) :
                new ObjectParameter("BaglantiID", typeof(int));
    
            var puanParameter = puan.HasValue ?
                new ObjectParameter("Puan", puan) :
                new ObjectParameter("Puan", typeof(decimal));
    
            var aciklamaParameter = aciklama != null ?
                new ObjectParameter("Aciklama", aciklama) :
                new ObjectParameter("Aciklama", typeof(string));
    
            var tarihParameter = tarih.HasValue ?
                new ObjectParameter("Tarih", tarih) :
                new ObjectParameter("Tarih", typeof(System.DateTime));
    
            var puanKategorisiParameter = puanKategorisi.HasValue ?
                new ObjectParameter("PuanKategorisi", puanKategorisi) :
                new ObjectParameter("PuanKategorisi", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("IUD_SadakatPuaniHesapla", baglantiIDParameter, puanParameter, aciklamaParameter, tarihParameter, puanKategorisiParameter);
        }
    
        public virtual ObjectResult<S_Resim_Result> S_Resim(Nullable<int> iD, Nullable<int> resimTipi_TipID29)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var resimTipi_TipID29Parameter = resimTipi_TipID29.HasValue ?
                new ObjectParameter("ResimTipi_TipID29", resimTipi_TipID29) :
                new ObjectParameter("ResimTipi_TipID29", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_Resim_Result>("S_Resim", iDParameter, resimTipi_TipID29Parameter);
        }
    
        public virtual ObjectResult<IUD_Gayrimenkul_Result> IUD_Gayrimenkul(Nullable<bool> sil, Nullable<int> iD, Nullable<int> projeID, Nullable<int> gayrimenkulTipi_TipID84, Nullable<int> yapiTipi_TipID85, Nullable<int> blokID, Nullable<int> blokGiris_TipID86, Nullable<int> katID, string daireNo, Nullable<int> yon_TipID87, Nullable<int> manzara_TipID88, Nullable<int> odaSayisi, Nullable<decimal> brutM2, Nullable<decimal> netM2, Nullable<decimal> eklentiM2, Nullable<decimal> katBrutM2, Nullable<decimal> balkonM2, Nullable<decimal> terasM2, Nullable<decimal> bahceM2, Nullable<decimal> genelBrutM2, Nullable<decimal> adaM2, Nullable<decimal> paftaM2, Nullable<decimal> parselM2, Nullable<int> otoParkAdedi, string otoParkNo, Nullable<int> otoParkTipi_TipID89, string tapuKat, string tapuBagNo, string tapuBlok, Nullable<bool> satisaKapali, string satisaKapaliNotu, Nullable<bool> aktif, Nullable<System.DateTime> tarih, Nullable<int> olusturanKullaniciID, Nullable<System.DateTime> olusturanTarih, Nullable<int> degistirenKullaniciID, Nullable<System.DateTime> degistirenTarih, Nullable<decimal> fiyat, Nullable<int> dovizID, Nullable<bool> kdv, Nullable<decimal> kdvOrani)
        {
            var silParameter = sil.HasValue ?
                new ObjectParameter("Sil", sil) :
                new ObjectParameter("Sil", typeof(bool));
    
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var projeIDParameter = projeID.HasValue ?
                new ObjectParameter("ProjeID", projeID) :
                new ObjectParameter("ProjeID", typeof(int));
    
            var gayrimenkulTipi_TipID84Parameter = gayrimenkulTipi_TipID84.HasValue ?
                new ObjectParameter("GayrimenkulTipi_TipID84", gayrimenkulTipi_TipID84) :
                new ObjectParameter("GayrimenkulTipi_TipID84", typeof(int));
    
            var yapiTipi_TipID85Parameter = yapiTipi_TipID85.HasValue ?
                new ObjectParameter("YapiTipi_TipID85", yapiTipi_TipID85) :
                new ObjectParameter("YapiTipi_TipID85", typeof(int));
    
            var blokIDParameter = blokID.HasValue ?
                new ObjectParameter("BlokID", blokID) :
                new ObjectParameter("BlokID", typeof(int));
    
            var blokGiris_TipID86Parameter = blokGiris_TipID86.HasValue ?
                new ObjectParameter("BlokGiris_TipID86", blokGiris_TipID86) :
                new ObjectParameter("BlokGiris_TipID86", typeof(int));
    
            var katIDParameter = katID.HasValue ?
                new ObjectParameter("KatID", katID) :
                new ObjectParameter("KatID", typeof(int));
    
            var daireNoParameter = daireNo != null ?
                new ObjectParameter("DaireNo", daireNo) :
                new ObjectParameter("DaireNo", typeof(string));
    
            var yon_TipID87Parameter = yon_TipID87.HasValue ?
                new ObjectParameter("Yon_TipID87", yon_TipID87) :
                new ObjectParameter("Yon_TipID87", typeof(int));
    
            var manzara_TipID88Parameter = manzara_TipID88.HasValue ?
                new ObjectParameter("Manzara_TipID88", manzara_TipID88) :
                new ObjectParameter("Manzara_TipID88", typeof(int));
    
            var odaSayisiParameter = odaSayisi.HasValue ?
                new ObjectParameter("OdaSayisi", odaSayisi) :
                new ObjectParameter("OdaSayisi", typeof(int));
    
            var brutM2Parameter = brutM2.HasValue ?
                new ObjectParameter("BrutM2", brutM2) :
                new ObjectParameter("BrutM2", typeof(decimal));
    
            var netM2Parameter = netM2.HasValue ?
                new ObjectParameter("NetM2", netM2) :
                new ObjectParameter("NetM2", typeof(decimal));
    
            var eklentiM2Parameter = eklentiM2.HasValue ?
                new ObjectParameter("EklentiM2", eklentiM2) :
                new ObjectParameter("EklentiM2", typeof(decimal));
    
            var katBrutM2Parameter = katBrutM2.HasValue ?
                new ObjectParameter("KatBrutM2", katBrutM2) :
                new ObjectParameter("KatBrutM2", typeof(decimal));
    
            var balkonM2Parameter = balkonM2.HasValue ?
                new ObjectParameter("BalkonM2", balkonM2) :
                new ObjectParameter("BalkonM2", typeof(decimal));
    
            var terasM2Parameter = terasM2.HasValue ?
                new ObjectParameter("TerasM2", terasM2) :
                new ObjectParameter("TerasM2", typeof(decimal));
    
            var bahceM2Parameter = bahceM2.HasValue ?
                new ObjectParameter("BahceM2", bahceM2) :
                new ObjectParameter("BahceM2", typeof(decimal));
    
            var genelBrutM2Parameter = genelBrutM2.HasValue ?
                new ObjectParameter("GenelBrutM2", genelBrutM2) :
                new ObjectParameter("GenelBrutM2", typeof(decimal));
    
            var adaM2Parameter = adaM2.HasValue ?
                new ObjectParameter("AdaM2", adaM2) :
                new ObjectParameter("AdaM2", typeof(decimal));
    
            var paftaM2Parameter = paftaM2.HasValue ?
                new ObjectParameter("PaftaM2", paftaM2) :
                new ObjectParameter("PaftaM2", typeof(decimal));
    
            var parselM2Parameter = parselM2.HasValue ?
                new ObjectParameter("ParselM2", parselM2) :
                new ObjectParameter("ParselM2", typeof(decimal));
    
            var otoParkAdediParameter = otoParkAdedi.HasValue ?
                new ObjectParameter("OtoParkAdedi", otoParkAdedi) :
                new ObjectParameter("OtoParkAdedi", typeof(int));
    
            var otoParkNoParameter = otoParkNo != null ?
                new ObjectParameter("OtoParkNo", otoParkNo) :
                new ObjectParameter("OtoParkNo", typeof(string));
    
            var otoParkTipi_TipID89Parameter = otoParkTipi_TipID89.HasValue ?
                new ObjectParameter("OtoParkTipi_TipID89", otoParkTipi_TipID89) :
                new ObjectParameter("OtoParkTipi_TipID89", typeof(int));
    
            var tapuKatParameter = tapuKat != null ?
                new ObjectParameter("TapuKat", tapuKat) :
                new ObjectParameter("TapuKat", typeof(string));
    
            var tapuBagNoParameter = tapuBagNo != null ?
                new ObjectParameter("TapuBagNo", tapuBagNo) :
                new ObjectParameter("TapuBagNo", typeof(string));
    
            var tapuBlokParameter = tapuBlok != null ?
                new ObjectParameter("TapuBlok", tapuBlok) :
                new ObjectParameter("TapuBlok", typeof(string));
    
            var satisaKapaliParameter = satisaKapali.HasValue ?
                new ObjectParameter("SatisaKapali", satisaKapali) :
                new ObjectParameter("SatisaKapali", typeof(bool));
    
            var satisaKapaliNotuParameter = satisaKapaliNotu != null ?
                new ObjectParameter("SatisaKapaliNotu", satisaKapaliNotu) :
                new ObjectParameter("SatisaKapaliNotu", typeof(string));
    
            var aktifParameter = aktif.HasValue ?
                new ObjectParameter("Aktif", aktif) :
                new ObjectParameter("Aktif", typeof(bool));
    
            var tarihParameter = tarih.HasValue ?
                new ObjectParameter("Tarih", tarih) :
                new ObjectParameter("Tarih", typeof(System.DateTime));
    
            var olusturanKullaniciIDParameter = olusturanKullaniciID.HasValue ?
                new ObjectParameter("OlusturanKullaniciID", olusturanKullaniciID) :
                new ObjectParameter("OlusturanKullaniciID", typeof(int));
    
            var olusturanTarihParameter = olusturanTarih.HasValue ?
                new ObjectParameter("OlusturanTarih", olusturanTarih) :
                new ObjectParameter("OlusturanTarih", typeof(System.DateTime));
    
            var degistirenKullaniciIDParameter = degistirenKullaniciID.HasValue ?
                new ObjectParameter("DegistirenKullaniciID", degistirenKullaniciID) :
                new ObjectParameter("DegistirenKullaniciID", typeof(int));
    
            var degistirenTarihParameter = degistirenTarih.HasValue ?
                new ObjectParameter("DegistirenTarih", degistirenTarih) :
                new ObjectParameter("DegistirenTarih", typeof(System.DateTime));
    
            var fiyatParameter = fiyat.HasValue ?
                new ObjectParameter("Fiyat", fiyat) :
                new ObjectParameter("Fiyat", typeof(decimal));
    
            var dovizIDParameter = dovizID.HasValue ?
                new ObjectParameter("DovizID", dovizID) :
                new ObjectParameter("DovizID", typeof(int));
    
            var kdvParameter = kdv.HasValue ?
                new ObjectParameter("Kdv", kdv) :
                new ObjectParameter("Kdv", typeof(bool));
    
            var kdvOraniParameter = kdvOrani.HasValue ?
                new ObjectParameter("KdvOrani", kdvOrani) :
                new ObjectParameter("KdvOrani", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IUD_Gayrimenkul_Result>("IUD_Gayrimenkul", silParameter, iDParameter, projeIDParameter, gayrimenkulTipi_TipID84Parameter, yapiTipi_TipID85Parameter, blokIDParameter, blokGiris_TipID86Parameter, katIDParameter, daireNoParameter, yon_TipID87Parameter, manzara_TipID88Parameter, odaSayisiParameter, brutM2Parameter, netM2Parameter, eklentiM2Parameter, katBrutM2Parameter, balkonM2Parameter, terasM2Parameter, bahceM2Parameter, genelBrutM2Parameter, adaM2Parameter, paftaM2Parameter, parselM2Parameter, otoParkAdediParameter, otoParkNoParameter, otoParkTipi_TipID89Parameter, tapuKatParameter, tapuBagNoParameter, tapuBlokParameter, satisaKapaliParameter, satisaKapaliNotuParameter, aktifParameter, tarihParameter, olusturanKullaniciIDParameter, olusturanTarihParameter, degistirenKullaniciIDParameter, degistirenTarihParameter, fiyatParameter, dovizIDParameter, kdvParameter, kdvOraniParameter);
        }
    
        public virtual ObjectResult<S_Gayrimenkul_Result> S_Gayrimenkul(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_Gayrimenkul_Result>("S_Gayrimenkul", iDParameter);
        }
    
        public virtual ObjectResult<S_QueryCalistir_Result> S_QueryCalistir(string query)
        {
            var queryParameter = query != null ?
                new ObjectParameter("Query", query) :
                new ObjectParameter("Query", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_QueryCalistir_Result>("S_QueryCalistir", queryParameter);
        }
    
        public virtual ObjectResult<S_Personel_Result> S_Personel(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_Personel_Result>("S_Personel", iDParameter);
        }
    
        public virtual ObjectResult<S_BaglantiHareketleri_Result> S_BaglantiHareketleri(Nullable<int> iD, Nullable<int> baglantiID)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var baglantiIDParameter = baglantiID.HasValue ?
                new ObjectParameter("BaglantiID", baglantiID) :
                new ObjectParameter("BaglantiID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_BaglantiHareketleri_Result>("S_BaglantiHareketleri", iDParameter, baglantiIDParameter);
        }
    
        public virtual ObjectResult<S_KullaniciGirisKontrol_Result> S_KullaniciGirisKontrol(string kullaniciAdi, string parola)
        {
            var kullaniciAdiParameter = kullaniciAdi != null ?
                new ObjectParameter("KullaniciAdi", kullaniciAdi) :
                new ObjectParameter("KullaniciAdi", typeof(string));
    
            var parolaParameter = parola != null ?
                new ObjectParameter("Parola", parola) :
                new ObjectParameter("Parola", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_KullaniciGirisKontrol_Result>("S_KullaniciGirisKontrol", kullaniciAdiParameter, parolaParameter);
        }
    
        public virtual ObjectResult<S_DurdurulacakBaglantiHareketleri_Result> S_DurdurulacakBaglantiHareketleri(Nullable<int> baglanti)
        {
            var baglantiParameter = baglanti.HasValue ?
                new ObjectParameter("Baglanti", baglanti) :
                new ObjectParameter("Baglanti", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_DurdurulacakBaglantiHareketleri_Result>("S_DurdurulacakBaglantiHareketleri", baglantiParameter);
        }
    
        public virtual ObjectResult<S_Ofis_Result> S_Ofis(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_Ofis_Result>("S_Ofis", iDParameter);
        }
    
        public virtual ObjectResult<IUD_BaglantiHareketleri_Result> IUD_BaglantiHareketleri(Nullable<bool> sil, Nullable<int> iD, Nullable<int> baglantiID, Nullable<int> personelID, Nullable<System.DateTime> tarih, Nullable<System.DateTime> saat, string sure, Nullable<int> ofisID, Nullable<int> hareketTipi_TipID17, Nullable<int> hareketKaynagi_TipID43, string aciklamaNotu, Nullable<int> hareketDurumTipi_TipID26, Nullable<int> hareketPuani, Nullable<bool> devamEdenHareket, Nullable<int> durdurulanHareketID, Nullable<bool> randevu, Nullable<int> randevuID, Nullable<bool> hatirlatma, Nullable<int> hatirlatmaID, Nullable<int> kampanyaTanitimiID, Nullable<bool> aktif, Nullable<int> olusturanKullaniciID, Nullable<System.DateTime> olusturanTarih, Nullable<int> degistirenKullaniciID, Nullable<System.DateTime> degistirenTarih, Nullable<bool> tanitimTercihiSMS, Nullable<bool> tanitimTercihiEPosta, Nullable<bool> tanitimTercihiTelefon, Nullable<int> ePostaHareketID, Nullable<int> sesKaydiHareketID, Nullable<int> cepKisaMesajHareketiID)
        {
            var silParameter = sil.HasValue ?
                new ObjectParameter("Sil", sil) :
                new ObjectParameter("Sil", typeof(bool));
    
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var baglantiIDParameter = baglantiID.HasValue ?
                new ObjectParameter("BaglantiID", baglantiID) :
                new ObjectParameter("BaglantiID", typeof(int));
    
            var personelIDParameter = personelID.HasValue ?
                new ObjectParameter("PersonelID", personelID) :
                new ObjectParameter("PersonelID", typeof(int));
    
            var tarihParameter = tarih.HasValue ?
                new ObjectParameter("Tarih", tarih) :
                new ObjectParameter("Tarih", typeof(System.DateTime));
    
            var saatParameter = saat.HasValue ?
                new ObjectParameter("Saat", saat) :
                new ObjectParameter("Saat", typeof(System.DateTime));
    
            var sureParameter = sure != null ?
                new ObjectParameter("Sure", sure) :
                new ObjectParameter("Sure", typeof(string));
    
            var ofisIDParameter = ofisID.HasValue ?
                new ObjectParameter("OfisID", ofisID) :
                new ObjectParameter("OfisID", typeof(int));
    
            var hareketTipi_TipID17Parameter = hareketTipi_TipID17.HasValue ?
                new ObjectParameter("HareketTipi_TipID17", hareketTipi_TipID17) :
                new ObjectParameter("HareketTipi_TipID17", typeof(int));
    
            var hareketKaynagi_TipID43Parameter = hareketKaynagi_TipID43.HasValue ?
                new ObjectParameter("HareketKaynagi_TipID43", hareketKaynagi_TipID43) :
                new ObjectParameter("HareketKaynagi_TipID43", typeof(int));
    
            var aciklamaNotuParameter = aciklamaNotu != null ?
                new ObjectParameter("AciklamaNotu", aciklamaNotu) :
                new ObjectParameter("AciklamaNotu", typeof(string));
    
            var hareketDurumTipi_TipID26Parameter = hareketDurumTipi_TipID26.HasValue ?
                new ObjectParameter("HareketDurumTipi_TipID26", hareketDurumTipi_TipID26) :
                new ObjectParameter("HareketDurumTipi_TipID26", typeof(int));
    
            var hareketPuaniParameter = hareketPuani.HasValue ?
                new ObjectParameter("HareketPuani", hareketPuani) :
                new ObjectParameter("HareketPuani", typeof(int));
    
            var devamEdenHareketParameter = devamEdenHareket.HasValue ?
                new ObjectParameter("DevamEdenHareket", devamEdenHareket) :
                new ObjectParameter("DevamEdenHareket", typeof(bool));
    
            var durdurulanHareketIDParameter = durdurulanHareketID.HasValue ?
                new ObjectParameter("DurdurulanHareketID", durdurulanHareketID) :
                new ObjectParameter("DurdurulanHareketID", typeof(int));
    
            var randevuParameter = randevu.HasValue ?
                new ObjectParameter("Randevu", randevu) :
                new ObjectParameter("Randevu", typeof(bool));
    
            var randevuIDParameter = randevuID.HasValue ?
                new ObjectParameter("RandevuID", randevuID) :
                new ObjectParameter("RandevuID", typeof(int));
    
            var hatirlatmaParameter = hatirlatma.HasValue ?
                new ObjectParameter("Hatirlatma", hatirlatma) :
                new ObjectParameter("Hatirlatma", typeof(bool));
    
            var hatirlatmaIDParameter = hatirlatmaID.HasValue ?
                new ObjectParameter("HatirlatmaID", hatirlatmaID) :
                new ObjectParameter("HatirlatmaID", typeof(int));
    
            var kampanyaTanitimiIDParameter = kampanyaTanitimiID.HasValue ?
                new ObjectParameter("KampanyaTanitimiID", kampanyaTanitimiID) :
                new ObjectParameter("KampanyaTanitimiID", typeof(int));
    
            var aktifParameter = aktif.HasValue ?
                new ObjectParameter("Aktif", aktif) :
                new ObjectParameter("Aktif", typeof(bool));
    
            var olusturanKullaniciIDParameter = olusturanKullaniciID.HasValue ?
                new ObjectParameter("OlusturanKullaniciID", olusturanKullaniciID) :
                new ObjectParameter("OlusturanKullaniciID", typeof(int));
    
            var olusturanTarihParameter = olusturanTarih.HasValue ?
                new ObjectParameter("OlusturanTarih", olusturanTarih) :
                new ObjectParameter("OlusturanTarih", typeof(System.DateTime));
    
            var degistirenKullaniciIDParameter = degistirenKullaniciID.HasValue ?
                new ObjectParameter("DegistirenKullaniciID", degistirenKullaniciID) :
                new ObjectParameter("DegistirenKullaniciID", typeof(int));
    
            var degistirenTarihParameter = degistirenTarih.HasValue ?
                new ObjectParameter("DegistirenTarih", degistirenTarih) :
                new ObjectParameter("DegistirenTarih", typeof(System.DateTime));
    
            var tanitimTercihiSMSParameter = tanitimTercihiSMS.HasValue ?
                new ObjectParameter("TanitimTercihiSMS", tanitimTercihiSMS) :
                new ObjectParameter("TanitimTercihiSMS", typeof(bool));
    
            var tanitimTercihiEPostaParameter = tanitimTercihiEPosta.HasValue ?
                new ObjectParameter("TanitimTercihiEPosta", tanitimTercihiEPosta) :
                new ObjectParameter("TanitimTercihiEPosta", typeof(bool));
    
            var tanitimTercihiTelefonParameter = tanitimTercihiTelefon.HasValue ?
                new ObjectParameter("TanitimTercihiTelefon", tanitimTercihiTelefon) :
                new ObjectParameter("TanitimTercihiTelefon", typeof(bool));
    
            var ePostaHareketIDParameter = ePostaHareketID.HasValue ?
                new ObjectParameter("EPostaHareketID", ePostaHareketID) :
                new ObjectParameter("EPostaHareketID", typeof(int));
    
            var sesKaydiHareketIDParameter = sesKaydiHareketID.HasValue ?
                new ObjectParameter("SesKaydiHareketID", sesKaydiHareketID) :
                new ObjectParameter("SesKaydiHareketID", typeof(int));
    
            var cepKisaMesajHareketiIDParameter = cepKisaMesajHareketiID.HasValue ?
                new ObjectParameter("CepKisaMesajHareketiID", cepKisaMesajHareketiID) :
                new ObjectParameter("CepKisaMesajHareketiID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IUD_BaglantiHareketleri_Result>("IUD_BaglantiHareketleri", silParameter, iDParameter, baglantiIDParameter, personelIDParameter, tarihParameter, saatParameter, sureParameter, ofisIDParameter, hareketTipi_TipID17Parameter, hareketKaynagi_TipID43Parameter, aciklamaNotuParameter, hareketDurumTipi_TipID26Parameter, hareketPuaniParameter, devamEdenHareketParameter, durdurulanHareketIDParameter, randevuParameter, randevuIDParameter, hatirlatmaParameter, hatirlatmaIDParameter, kampanyaTanitimiIDParameter, aktifParameter, olusturanKullaniciIDParameter, olusturanTarihParameter, degistirenKullaniciIDParameter, degistirenTarihParameter, tanitimTercihiSMSParameter, tanitimTercihiEPostaParameter, tanitimTercihiTelefonParameter, ePostaHareketIDParameter, sesKaydiHareketIDParameter, cepKisaMesajHareketiIDParameter);
        }
    
        public virtual ObjectResult<IUD_KullaniciAyarlari_Result> IUD_KullaniciAyarlari(Nullable<int> kullaniciID, string tema, string sikKullanilanlar, byte[] quickAccessToolbarNesneleri, string quickAccessToolbarPozisyon, Nullable<bool> solNavigasyonAcikMi, Nullable<int> solNavigasyonGenislik, Nullable<int> dashboardID, Nullable<bool> dashboardYenilensin, Nullable<int> dashboardSuresi, Nullable<int> hangiEkrandanIslemYapidi)
        {
            var kullaniciIDParameter = kullaniciID.HasValue ?
                new ObjectParameter("KullaniciID", kullaniciID) :
                new ObjectParameter("KullaniciID", typeof(int));
    
            var temaParameter = tema != null ?
                new ObjectParameter("Tema", tema) :
                new ObjectParameter("Tema", typeof(string));
    
            var sikKullanilanlarParameter = sikKullanilanlar != null ?
                new ObjectParameter("SikKullanilanlar", sikKullanilanlar) :
                new ObjectParameter("SikKullanilanlar", typeof(string));
    
            var quickAccessToolbarNesneleriParameter = quickAccessToolbarNesneleri != null ?
                new ObjectParameter("QuickAccessToolbarNesneleri", quickAccessToolbarNesneleri) :
                new ObjectParameter("QuickAccessToolbarNesneleri", typeof(byte[]));
    
            var quickAccessToolbarPozisyonParameter = quickAccessToolbarPozisyon != null ?
                new ObjectParameter("QuickAccessToolbarPozisyon", quickAccessToolbarPozisyon) :
                new ObjectParameter("QuickAccessToolbarPozisyon", typeof(string));
    
            var solNavigasyonAcikMiParameter = solNavigasyonAcikMi.HasValue ?
                new ObjectParameter("SolNavigasyonAcikMi", solNavigasyonAcikMi) :
                new ObjectParameter("SolNavigasyonAcikMi", typeof(bool));
    
            var solNavigasyonGenislikParameter = solNavigasyonGenislik.HasValue ?
                new ObjectParameter("SolNavigasyonGenislik", solNavigasyonGenislik) :
                new ObjectParameter("SolNavigasyonGenislik", typeof(int));
    
            var dashboardIDParameter = dashboardID.HasValue ?
                new ObjectParameter("DashboardID", dashboardID) :
                new ObjectParameter("DashboardID", typeof(int));
    
            var dashboardYenilensinParameter = dashboardYenilensin.HasValue ?
                new ObjectParameter("DashboardYenilensin", dashboardYenilensin) :
                new ObjectParameter("DashboardYenilensin", typeof(bool));
    
            var dashboardSuresiParameter = dashboardSuresi.HasValue ?
                new ObjectParameter("DashboardSuresi", dashboardSuresi) :
                new ObjectParameter("DashboardSuresi", typeof(int));
    
            var hangiEkrandanIslemYapidiParameter = hangiEkrandanIslemYapidi.HasValue ?
                new ObjectParameter("HangiEkrandanIslemYapidi", hangiEkrandanIslemYapidi) :
                new ObjectParameter("HangiEkrandanIslemYapidi", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IUD_KullaniciAyarlari_Result>("IUD_KullaniciAyarlari", kullaniciIDParameter, temaParameter, sikKullanilanlarParameter, quickAccessToolbarNesneleriParameter, quickAccessToolbarPozisyonParameter, solNavigasyonAcikMiParameter, solNavigasyonGenislikParameter, dashboardIDParameter, dashboardYenilensinParameter, dashboardSuresiParameter, hangiEkrandanIslemYapidiParameter);
        }
    
        public virtual ObjectResult<S_Menu_Result> S_Menu(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_Menu_Result>("S_Menu", iDParameter);
        }
    
        public virtual ObjectResult<S_AyarKarakter_Result> S_AyarKarakter(Nullable<int> iD, Nullable<int> dilID)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var dilIDParameter = dilID.HasValue ?
                new ObjectParameter("DilID", dilID) :
                new ObjectParameter("DilID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_AyarKarakter_Result>("S_AyarKarakter", iDParameter, dilIDParameter);
        }
    
        public virtual ObjectResult<S_Dashboard_Result> S_Dashboard(Nullable<int> dashboardID, Nullable<int> dilID)
        {
            var dashboardIDParameter = dashboardID.HasValue ?
                new ObjectParameter("DashboardID", dashboardID) :
                new ObjectParameter("DashboardID", typeof(int));
    
            var dilIDParameter = dilID.HasValue ?
                new ObjectParameter("DilID", dilID) :
                new ObjectParameter("DilID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_Dashboard_Result>("S_Dashboard", dashboardIDParameter, dilIDParameter);
        }
    
        public virtual ObjectResult<byte[]> S_DosyaGet(string dosyaYolu)
        {
            var dosyaYoluParameter = dosyaYolu != null ?
                new ObjectParameter("DosyaYolu", dosyaYolu) :
                new ObjectParameter("DosyaYolu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<byte[]>("S_DosyaGet", dosyaYoluParameter);
        }
    
        public virtual ObjectResult<S_Evraklar_Result> S_Evraklar(Nullable<int> iD, Nullable<bool> devexpressDashboardMu, Nullable<int> dilID)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var devexpressDashboardMuParameter = devexpressDashboardMu.HasValue ?
                new ObjectParameter("DevexpressDashboardMu", devexpressDashboardMu) :
                new ObjectParameter("DevexpressDashboardMu", typeof(bool));
    
            var dilIDParameter = dilID.HasValue ?
                new ObjectParameter("DilID", dilID) :
                new ObjectParameter("DilID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_Evraklar_Result>("S_Evraklar", iDParameter, devexpressDashboardMuParameter, dilIDParameter);
        }
    
        public virtual ObjectResult<S_EvrakDataSourceCalistir_Result> S_EvrakDataSourceCalistir(Nullable<int> dilID, Nullable<int> evrakID, Nullable<int> iD01, Nullable<int> iD02, Nullable<int> iD03, Nullable<int> iD04, Nullable<int> iD05, Nullable<int> iD06, Nullable<int> iD07, Nullable<int> iD08, Nullable<int> iD09, Nullable<int> iD10)
        {
            var dilIDParameter = dilID.HasValue ?
                new ObjectParameter("DilID", dilID) :
                new ObjectParameter("DilID", typeof(int));
    
            var evrakIDParameter = evrakID.HasValue ?
                new ObjectParameter("EvrakID", evrakID) :
                new ObjectParameter("EvrakID", typeof(int));
    
            var iD01Parameter = iD01.HasValue ?
                new ObjectParameter("ID01", iD01) :
                new ObjectParameter("ID01", typeof(int));
    
            var iD02Parameter = iD02.HasValue ?
                new ObjectParameter("ID02", iD02) :
                new ObjectParameter("ID02", typeof(int));
    
            var iD03Parameter = iD03.HasValue ?
                new ObjectParameter("ID03", iD03) :
                new ObjectParameter("ID03", typeof(int));
    
            var iD04Parameter = iD04.HasValue ?
                new ObjectParameter("ID04", iD04) :
                new ObjectParameter("ID04", typeof(int));
    
            var iD05Parameter = iD05.HasValue ?
                new ObjectParameter("ID05", iD05) :
                new ObjectParameter("ID05", typeof(int));
    
            var iD06Parameter = iD06.HasValue ?
                new ObjectParameter("ID06", iD06) :
                new ObjectParameter("ID06", typeof(int));
    
            var iD07Parameter = iD07.HasValue ?
                new ObjectParameter("ID07", iD07) :
                new ObjectParameter("ID07", typeof(int));
    
            var iD08Parameter = iD08.HasValue ?
                new ObjectParameter("ID08", iD08) :
                new ObjectParameter("ID08", typeof(int));
    
            var iD09Parameter = iD09.HasValue ?
                new ObjectParameter("ID09", iD09) :
                new ObjectParameter("ID09", typeof(int));
    
            var iD10Parameter = iD10.HasValue ?
                new ObjectParameter("ID10", iD10) :
                new ObjectParameter("ID10", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_EvrakDataSourceCalistir_Result>("S_EvrakDataSourceCalistir", dilIDParameter, evrakIDParameter, iD01Parameter, iD02Parameter, iD03Parameter, iD04Parameter, iD05Parameter, iD06Parameter, iD07Parameter, iD08Parameter, iD09Parameter, iD10Parameter);
        }
    
        public virtual ObjectResult<IUD_Evraklar_Result> IUD_Evraklar(Nullable<int> islemTipi, Nullable<int> iD, byte[] rapor, string evrakTanimBasligi, string aciklamalar, Nullable<int> evrakGosterimYeriID, Nullable<int> durumSecID_400, Nullable<bool> aktifMi, Nullable<bool> dataSourceKullaniciTanimliMi, Nullable<int> yetkilendirmeKisID_201, Nullable<int> siraNo, Nullable<bool> devexpressDashboardMu, Nullable<int> kullaniciID)
        {
            var islemTipiParameter = islemTipi.HasValue ?
                new ObjectParameter("IslemTipi", islemTipi) :
                new ObjectParameter("IslemTipi", typeof(int));
    
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var raporParameter = rapor != null ?
                new ObjectParameter("Rapor", rapor) :
                new ObjectParameter("Rapor", typeof(byte[]));
    
            var evrakTanimBasligiParameter = evrakTanimBasligi != null ?
                new ObjectParameter("EvrakTanimBasligi", evrakTanimBasligi) :
                new ObjectParameter("EvrakTanimBasligi", typeof(string));
    
            var aciklamalarParameter = aciklamalar != null ?
                new ObjectParameter("Aciklamalar", aciklamalar) :
                new ObjectParameter("Aciklamalar", typeof(string));
    
            var evrakGosterimYeriIDParameter = evrakGosterimYeriID.HasValue ?
                new ObjectParameter("EvrakGosterimYeriID", evrakGosterimYeriID) :
                new ObjectParameter("EvrakGosterimYeriID", typeof(int));
    
            var durumSecID_400Parameter = durumSecID_400.HasValue ?
                new ObjectParameter("DurumSecID_400", durumSecID_400) :
                new ObjectParameter("DurumSecID_400", typeof(int));
    
            var aktifMiParameter = aktifMi.HasValue ?
                new ObjectParameter("AktifMi", aktifMi) :
                new ObjectParameter("AktifMi", typeof(bool));
    
            var dataSourceKullaniciTanimliMiParameter = dataSourceKullaniciTanimliMi.HasValue ?
                new ObjectParameter("DataSourceKullaniciTanimliMi", dataSourceKullaniciTanimliMi) :
                new ObjectParameter("DataSourceKullaniciTanimliMi", typeof(bool));
    
            var yetkilendirmeKisID_201Parameter = yetkilendirmeKisID_201.HasValue ?
                new ObjectParameter("YetkilendirmeKisID_201", yetkilendirmeKisID_201) :
                new ObjectParameter("YetkilendirmeKisID_201", typeof(int));
    
            var siraNoParameter = siraNo.HasValue ?
                new ObjectParameter("SiraNo", siraNo) :
                new ObjectParameter("SiraNo", typeof(int));
    
            var devexpressDashboardMuParameter = devexpressDashboardMu.HasValue ?
                new ObjectParameter("DevexpressDashboardMu", devexpressDashboardMu) :
                new ObjectParameter("DevexpressDashboardMu", typeof(bool));
    
            var kullaniciIDParameter = kullaniciID.HasValue ?
                new ObjectParameter("KullaniciID", kullaniciID) :
                new ObjectParameter("KullaniciID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IUD_Evraklar_Result>("IUD_Evraklar", islemTipiParameter, iDParameter, raporParameter, evrakTanimBasligiParameter, aciklamalarParameter, evrakGosterimYeriIDParameter, durumSecID_400Parameter, aktifMiParameter, dataSourceKullaniciTanimliMiParameter, yetkilendirmeKisID_201Parameter, siraNoParameter, devexpressDashboardMuParameter, kullaniciIDParameter);
        }
    
        public virtual int S_DosyaDelete(string dosyaYolu)
        {
            var dosyaYoluParameter = dosyaYolu != null ?
                new ObjectParameter("DosyaYolu", dosyaYolu) :
                new ObjectParameter("DosyaYolu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("S_DosyaDelete", dosyaYoluParameter);
        }
    
        public virtual int S_DosyaInsert(byte[] dOSYA, string dOSYA_YOLU, string dOSYA_ADI)
        {
            var dOSYAParameter = dOSYA != null ?
                new ObjectParameter("DOSYA", dOSYA) :
                new ObjectParameter("DOSYA", typeof(byte[]));
    
            var dOSYA_YOLUParameter = dOSYA_YOLU != null ?
                new ObjectParameter("DOSYA_YOLU", dOSYA_YOLU) :
                new ObjectParameter("DOSYA_YOLU", typeof(string));
    
            var dOSYA_ADIParameter = dOSYA_ADI != null ?
                new ObjectParameter("DOSYA_ADI", dOSYA_ADI) :
                new ObjectParameter("DOSYA_ADI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("S_DosyaInsert", dOSYAParameter, dOSYA_YOLUParameter, dOSYA_ADIParameter);
        }
    
        public virtual ObjectResult<S_Kullanici_Result1> S_Kullanici(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_Kullanici_Result1>("S_Kullanici", iDParameter);
        }
    
        public virtual ObjectResult<S_EsnekKayitQueryCalistir_Result> S_EsnekKayitQueryCalistir(string query, Nullable<int> oturumID, Nullable<int> kullaniciID)
        {
            var queryParameter = query != null ?
                new ObjectParameter("Query", query) :
                new ObjectParameter("Query", typeof(string));
    
            var oturumIDParameter = oturumID.HasValue ?
                new ObjectParameter("OturumID", oturumID) :
                new ObjectParameter("OturumID", typeof(int));
    
            var kullaniciIDParameter = kullaniciID.HasValue ?
                new ObjectParameter("KullaniciID", kullaniciID) :
                new ObjectParameter("KullaniciID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_EsnekKayitQueryCalistir_Result>("S_EsnekKayitQueryCalistir", queryParameter, oturumIDParameter, kullaniciIDParameter);
        }
    
        public virtual ObjectResult<S_EsnekKayitQuery_Result> S_EsnekKayitQuery(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_EsnekKayitQuery_Result>("S_EsnekKayitQuery", iDParameter);
        }
    
        public virtual ObjectResult<IUD_EsnekKayit_Result> IUD_EsnekKayit(Nullable<int> controlTipi, string secilenKayitIDs, Nullable<int> kayitID, Nullable<int> queryID, Nullable<int> iDeger, string nDeger, Nullable<decimal> dDeger, Nullable<System.DateTime> tDeger)
        {
            var controlTipiParameter = controlTipi.HasValue ?
                new ObjectParameter("ControlTipi", controlTipi) :
                new ObjectParameter("ControlTipi", typeof(int));
    
            var secilenKayitIDsParameter = secilenKayitIDs != null ?
                new ObjectParameter("SecilenKayitIDs", secilenKayitIDs) :
                new ObjectParameter("SecilenKayitIDs", typeof(string));
    
            var kayitIDParameter = kayitID.HasValue ?
                new ObjectParameter("KayitID", kayitID) :
                new ObjectParameter("KayitID", typeof(int));
    
            var queryIDParameter = queryID.HasValue ?
                new ObjectParameter("QueryID", queryID) :
                new ObjectParameter("QueryID", typeof(int));
    
            var iDegerParameter = iDeger.HasValue ?
                new ObjectParameter("iDeger", iDeger) :
                new ObjectParameter("iDeger", typeof(int));
    
            var nDegerParameter = nDeger != null ?
                new ObjectParameter("nDeger", nDeger) :
                new ObjectParameter("nDeger", typeof(string));
    
            var dDegerParameter = dDeger.HasValue ?
                new ObjectParameter("dDeger", dDeger) :
                new ObjectParameter("dDeger", typeof(decimal));
    
            var tDegerParameter = tDeger.HasValue ?
                new ObjectParameter("tDeger", tDeger) :
                new ObjectParameter("tDeger", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IUD_EsnekKayit_Result>("IUD_EsnekKayit", controlTipiParameter, secilenKayitIDsParameter, kayitIDParameter, queryIDParameter, iDegerParameter, nDegerParameter, dDegerParameter, tDegerParameter);
        }
    
        public virtual ObjectResult<S_Takim_Result> S_Takim(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_Takim_Result>("S_Takim", iDParameter);
        }
    
        public virtual ObjectResult<IUD_Takim_Result> IUD_Takim(Nullable<bool> aktif, Nullable<int> degistirenKullaniciID, Nullable<System.DateTime> degistirenKullaniciTarih, Nullable<int> iD, Nullable<int> kullaniciID, Nullable<int> olusturanKullaniciID, Nullable<System.DateTime> olusturanKullaniciTarih, Nullable<bool> sil, string takimAdi, string takimKodu, Nullable<System.DateTime> tarih)
        {
            var aktifParameter = aktif.HasValue ?
                new ObjectParameter("Aktif", aktif) :
                new ObjectParameter("Aktif", typeof(bool));
    
            var degistirenKullaniciIDParameter = degistirenKullaniciID.HasValue ?
                new ObjectParameter("DegistirenKullaniciID", degistirenKullaniciID) :
                new ObjectParameter("DegistirenKullaniciID", typeof(int));
    
            var degistirenKullaniciTarihParameter = degistirenKullaniciTarih.HasValue ?
                new ObjectParameter("DegistirenKullaniciTarih", degistirenKullaniciTarih) :
                new ObjectParameter("DegistirenKullaniciTarih", typeof(System.DateTime));
    
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var kullaniciIDParameter = kullaniciID.HasValue ?
                new ObjectParameter("KullaniciID", kullaniciID) :
                new ObjectParameter("KullaniciID", typeof(int));
    
            var olusturanKullaniciIDParameter = olusturanKullaniciID.HasValue ?
                new ObjectParameter("OlusturanKullaniciID", olusturanKullaniciID) :
                new ObjectParameter("OlusturanKullaniciID", typeof(int));
    
            var olusturanKullaniciTarihParameter = olusturanKullaniciTarih.HasValue ?
                new ObjectParameter("OlusturanKullaniciTarih", olusturanKullaniciTarih) :
                new ObjectParameter("OlusturanKullaniciTarih", typeof(System.DateTime));
    
            var silParameter = sil.HasValue ?
                new ObjectParameter("Sil", sil) :
                new ObjectParameter("Sil", typeof(bool));
    
            var takimAdiParameter = takimAdi != null ?
                new ObjectParameter("TakimAdi", takimAdi) :
                new ObjectParameter("TakimAdi", typeof(string));
    
            var takimKoduParameter = takimKodu != null ?
                new ObjectParameter("TakimKodu", takimKodu) :
                new ObjectParameter("TakimKodu", typeof(string));
    
            var tarihParameter = tarih.HasValue ?
                new ObjectParameter("Tarih", tarih) :
                new ObjectParameter("Tarih", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IUD_Takim_Result>("IUD_Takim", aktifParameter, degistirenKullaniciIDParameter, degistirenKullaniciTarihParameter, iDParameter, kullaniciIDParameter, olusturanKullaniciIDParameter, olusturanKullaniciTarihParameter, silParameter, takimAdiParameter, takimKoduParameter, tarihParameter);
        }
    }
}
