//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarduckCRM
{
    using System;
    
    public partial class S_Kullanici_Result1
    {
        public int ID { get; set; }
        public string Ad { get; set; }
        public string KullaniciAdi { get; set; }
        public string Parola { get; set; }
        public bool Aktif { get; set; }
        public Nullable<System.DateTime> KayitTarih { get; set; }
        public bool Sil { get; set; }
        public string EPosta { get; set; }
        public int PersonelID { get; set; }
        public Nullable<System.DateTime> GirisTarihi { get; set; }
        public Nullable<System.DateTime> CikisTarihi { get; set; }
        public int ProfilID { get; set; }
    }
}
